-- 001_multi_operacion.sql
-- Retrofit WarePro (single-tenant) into multi-operacion (multi-sede).
-- Generated by gen_migration.php - review before applying.
-- NOTA: en MySQL/InnoDB cada ALTER/CREATE/DROP TABLE hace commit implicito,
-- por lo que este script NO es atomico como un todo. La red de seguridad
-- real es el mysqldump completo tomado ANTES de correr esto (ver deploy_migration.php).

-- 1. Catalogo de operaciones
CREATE TABLE IF NOT EXISTS `operaciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `activo` TINYINT(1) NOT NULL DEFAULT 1,
  `fecha_creacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `nombre` (`nombre`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `operaciones` (`nombre`) VALUES ('Cucuta');
SET @op_cucuta = LAST_INSERT_ID();

-- 2. usuarios: ancla de operacion + nuevo rol super_admin
ALTER TABLE `usuarios`
  MODIFY `cargo` ENUM('admin','supervisor','verificador','auxiliar','operador','lider','coplas','super_admin') NOT NULL,
  ADD COLUMN `operacion_id` INT NULL AFTER `cargo`;
UPDATE `usuarios` SET `operacion_id` = @op_cucuta WHERE `operacion_id` IS NULL;
ALTER TABLE `usuarios`
  MODIFY `operacion_id` INT NOT NULL,
  ADD CONSTRAINT `fk_usuarios_operacion` FOREIGN KEY (`operacion_id`) REFERENCES `operaciones`(`id`);

-- 3. Tablas operativas: agregar operacion_id, respaldar todo lo existente en Cucuta
ALTER TABLE `auditoria_ejecuciones` ADD COLUMN `operacion_id` INT NULL AFTER `id`;
UPDATE `auditoria_ejecuciones` SET `operacion_id` = @op_cucuta WHERE `operacion_id` IS NULL;
ALTER TABLE `auditoria_ejecuciones`
  MODIFY `operacion_id` INT NOT NULL,
  ADD CONSTRAINT `fk_auditoria_ejecuciones_operacion` FOREIGN KEY (`operacion_id`) REFERENCES `operaciones`(`id`);

ALTER TABLE `auditoria_ejecucion_respuestas` ADD COLUMN `operacion_id` INT NULL AFTER `id`;
UPDATE `auditoria_ejecucion_respuestas` SET `operacion_id` = @op_cucuta WHERE `operacion_id` IS NULL;
ALTER TABLE `auditoria_ejecucion_respuestas`
  MODIFY `operacion_id` INT NOT NULL,
  ADD CONSTRAINT `fk_auditoria_ejecucion_respuestas_operacion` FOREIGN KEY (`operacion_id`) REFERENCES `operaciones`(`id`);

ALTER TABLE `auditoria_zonas` ADD COLUMN `operacion_id` INT NULL AFTER `id`;
UPDATE `auditoria_zonas` SET `operacion_id` = @op_cucuta WHERE `operacion_id` IS NULL;
ALTER TABLE `auditoria_zonas`
  MODIFY `operacion_id` INT NOT NULL,
  ADD CONSTRAINT `fk_auditoria_zonas_operacion` FOREIGN KEY (`operacion_id`) REFERENCES `operaciones`(`id`);

ALTER TABLE `cargar_informativo` ADD COLUMN `operacion_id` INT NULL AFTER `id`;
UPDATE `cargar_informativo` SET `operacion_id` = @op_cucuta WHERE `operacion_id` IS NULL;
ALTER TABLE `cargar_informativo`
  MODIFY `operacion_id` INT NOT NULL,
  ADD CONSTRAINT `fk_cargar_informativo_operacion` FOREIGN KEY (`operacion_id`) REFERENCES `operaciones`(`id`);

ALTER TABLE `checklist_wip` ADD COLUMN `operacion_id` INT NULL AFTER `id`;
UPDATE `checklist_wip` SET `operacion_id` = @op_cucuta WHERE `operacion_id` IS NULL;
ALTER TABLE `checklist_wip`
  MODIFY `operacion_id` INT NOT NULL,
  ADD CONSTRAINT `fk_checklist_wip_operacion` FOREIGN KEY (`operacion_id`) REFERENCES `operaciones`(`id`);

ALTER TABLE `check_herramientas` ADD COLUMN `operacion_id` INT NULL AFTER `id`;
UPDATE `check_herramientas` SET `operacion_id` = @op_cucuta WHERE `operacion_id` IS NULL;
ALTER TABLE `check_herramientas`
  MODIFY `operacion_id` INT NOT NULL,
  ADD CONSTRAINT `fk_check_herramientas_operacion` FOREIGN KEY (`operacion_id`) REFERENCES `operaciones`(`id`);

ALTER TABLE `control_trampas` ADD COLUMN `operacion_id` INT NULL AFTER `id`;
UPDATE `control_trampas` SET `operacion_id` = @op_cucuta WHERE `operacion_id` IS NULL;
ALTER TABLE `control_trampas`
  MODIFY `operacion_id` INT NOT NULL,
  ADD CONSTRAINT `fk_control_trampas_operacion` FOREIGN KEY (`operacion_id`) REFERENCES `operaciones`(`id`);

ALTER TABLE `descansos` ADD COLUMN `operacion_id` INT NULL AFTER `id`;
UPDATE `descansos` SET `operacion_id` = @op_cucuta WHERE `operacion_id` IS NULL;
ALTER TABLE `descansos`
  MODIFY `operacion_id` INT NOT NULL,
  ADD CONSTRAINT `fk_descansos_operacion` FOREIGN KEY (`operacion_id`) REFERENCES `operaciones`(`id`);

ALTER TABLE `descargue` ADD COLUMN `operacion_id` INT NULL AFTER `id`;
UPDATE `descargue` SET `operacion_id` = @op_cucuta WHERE `operacion_id` IS NULL;
ALTER TABLE `descargue`
  MODIFY `operacion_id` INT NOT NULL,
  ADD CONSTRAINT `fk_descargue_operacion` FOREIGN KEY (`operacion_id`) REFERENCES `operaciones`(`id`);

ALTER TABLE `devoluciones` ADD COLUMN `operacion_id` INT NULL AFTER `id`;
UPDATE `devoluciones` SET `operacion_id` = @op_cucuta WHERE `operacion_id` IS NULL;
ALTER TABLE `devoluciones`
  MODIFY `operacion_id` INT NOT NULL,
  ADD CONSTRAINT `fk_devoluciones_operacion` FOREIGN KEY (`operacion_id`) REFERENCES `operaciones`(`id`);

ALTER TABLE `error_armado` ADD COLUMN `operacion_id` INT NULL AFTER `id`;
UPDATE `error_armado` SET `operacion_id` = @op_cucuta WHERE `operacion_id` IS NULL;
ALTER TABLE `error_armado`
  MODIFY `operacion_id` INT NOT NULL,
  ADD CONSTRAINT `fk_error_armado_operacion` FOREIGN KEY (`operacion_id`) REFERENCES `operaciones`(`id`);

ALTER TABLE `error_verificacion` ADD COLUMN `operacion_id` INT NULL AFTER `id`;
UPDATE `error_verificacion` SET `operacion_id` = @op_cucuta WHERE `operacion_id` IS NULL;
ALTER TABLE `error_verificacion`
  MODIFY `operacion_id` INT NOT NULL,
  ADD CONSTRAINT `fk_error_verificacion_operacion` FOREIGN KEY (`operacion_id`) REFERENCES `operaciones`(`id`);

ALTER TABLE `fefo_areas` ADD COLUMN `operacion_id` INT NULL AFTER `id`;
UPDATE `fefo_areas` SET `operacion_id` = @op_cucuta WHERE `operacion_id` IS NULL;
ALTER TABLE `fefo_areas`
  MODIFY `operacion_id` INT NOT NULL,
  ADD CONSTRAINT `fk_fefo_areas_operacion` FOREIGN KEY (`operacion_id`) REFERENCES `operaciones`(`id`);

ALTER TABLE `fefo_registros` ADD COLUMN `operacion_id` INT NULL AFTER `id`;
UPDATE `fefo_registros` SET `operacion_id` = @op_cucuta WHERE `operacion_id` IS NULL;
ALTER TABLE `fefo_registros`
  MODIFY `operacion_id` INT NOT NULL,
  ADD CONSTRAINT `fk_fefo_registros_operacion` FOREIGN KEY (`operacion_id`) REFERENCES `operaciones`(`id`);

ALTER TABLE `fefo_subareas` ADD COLUMN `operacion_id` INT NULL AFTER `id`;
UPDATE `fefo_subareas` SET `operacion_id` = @op_cucuta WHERE `operacion_id` IS NULL;
ALTER TABLE `fefo_subareas`
  MODIFY `operacion_id` INT NOT NULL,
  ADD CONSTRAINT `fk_fefo_subareas_operacion` FOREIGN KEY (`operacion_id`) REFERENCES `operaciones`(`id`);

ALTER TABLE `insumos` ADD COLUMN `operacion_id` INT NULL AFTER `id`;
UPDATE `insumos` SET `operacion_id` = @op_cucuta WHERE `operacion_id` IS NULL;
ALTER TABLE `insumos`
  MODIFY `operacion_id` INT NOT NULL,
  ADD CONSTRAINT `fk_insumos_operacion` FOREIGN KEY (`operacion_id`) REFERENCES `operaciones`(`id`);

ALTER TABLE `inventario_if` ADD COLUMN `operacion_id` INT NULL AFTER `id`;
UPDATE `inventario_if` SET `operacion_id` = @op_cucuta WHERE `operacion_id` IS NULL;
ALTER TABLE `inventario_if`
  MODIFY `operacion_id` INT NOT NULL,
  ADD CONSTRAINT `fk_inventario_if_operacion` FOREIGN KEY (`operacion_id`) REFERENCES `operaciones`(`id`);

ALTER TABLE `kpi_indicadores` ADD COLUMN `operacion_id` INT NULL AFTER `id`;
UPDATE `kpi_indicadores` SET `operacion_id` = @op_cucuta WHERE `operacion_id` IS NULL;
ALTER TABLE `kpi_indicadores`
  MODIFY `operacion_id` INT NOT NULL,
  ADD CONSTRAINT `fk_kpi_indicadores_operacion` FOREIGN KEY (`operacion_id`) REFERENCES `operaciones`(`id`);

ALTER TABLE `kpi_valores` ADD COLUMN `operacion_id` INT NULL AFTER `id`;
UPDATE `kpi_valores` SET `operacion_id` = @op_cucuta WHERE `operacion_id` IS NULL;
ALTER TABLE `kpi_valores`
  MODIFY `operacion_id` INT NOT NULL,
  ADD CONSTRAINT `fk_kpi_valores_operacion` FOREIGN KEY (`operacion_id`) REFERENCES `operaciones`(`id`);

ALTER TABLE `metas` ADD COLUMN `operacion_id` INT NULL AFTER `id`;
UPDATE `metas` SET `operacion_id` = @op_cucuta WHERE `operacion_id` IS NULL;
ALTER TABLE `metas`
  MODIFY `operacion_id` INT NOT NULL,
  ADD CONSTRAINT `fk_metas_operacion` FOREIGN KEY (`operacion_id`) REFERENCES `operaciones`(`id`);

ALTER TABLE `ows_cargue` ADD COLUMN `operacion_id` INT NULL AFTER `id`;
UPDATE `ows_cargue` SET `operacion_id` = @op_cucuta WHERE `operacion_id` IS NULL;
ALTER TABLE `ows_cargue`
  MODIFY `operacion_id` INT NOT NULL,
  ADD CONSTRAINT `fk_ows_cargue_operacion` FOREIGN KEY (`operacion_id`) REFERENCES `operaciones`(`id`);

ALTER TABLE `ows_reempaque` ADD COLUMN `operacion_id` INT NULL AFTER `id`;
UPDATE `ows_reempaque` SET `operacion_id` = @op_cucuta WHERE `operacion_id` IS NULL;
ALTER TABLE `ows_reempaque`
  MODIFY `operacion_id` INT NOT NULL,
  ADD CONSTRAINT `fk_ows_reempaque_operacion` FOREIGN KEY (`operacion_id`) REFERENCES `operaciones`(`id`);

ALTER TABLE `ows_revision` ADD COLUMN `operacion_id` INT NULL AFTER `id`;
UPDATE `ows_revision` SET `operacion_id` = @op_cucuta WHERE `operacion_id` IS NULL;
ALTER TABLE `ows_revision`
  MODIFY `operacion_id` INT NOT NULL,
  ADD CONSTRAINT `fk_ows_revision_operacion` FOREIGN KEY (`operacion_id`) REFERENCES `operaciones`(`id`);

ALTER TABLE `ows_vertimiento` ADD COLUMN `operacion_id` INT NULL AFTER `id`;
UPDATE `ows_vertimiento` SET `operacion_id` = @op_cucuta WHERE `operacion_id` IS NULL;
ALTER TABLE `ows_vertimiento`
  MODIFY `operacion_id` INT NOT NULL,
  ADD CONSTRAINT `fk_ows_vertimiento_operacion` FOREIGN KEY (`operacion_id`) REFERENCES `operaciones`(`id`);

ALTER TABLE `pasajes` ADD COLUMN `operacion_id` INT NULL AFTER `id`;
UPDATE `pasajes` SET `operacion_id` = @op_cucuta WHERE `operacion_id` IS NULL;
ALTER TABLE `pasajes`
  MODIFY `operacion_id` INT NOT NULL,
  ADD CONSTRAINT `fk_pasajes_operacion` FOREIGN KEY (`operacion_id`) REFERENCES `operaciones`(`id`);

ALTER TABLE `personal_activo` ADD COLUMN `operacion_id` INT NULL AFTER `id`;
UPDATE `personal_activo` SET `operacion_id` = @op_cucuta WHERE `operacion_id` IS NULL;
ALTER TABLE `personal_activo`
  MODIFY `operacion_id` INT NOT NULL,
  ADD CONSTRAINT `fk_personal_activo_operacion` FOREIGN KEY (`operacion_id`) REFERENCES `operaciones`(`id`);

ALTER TABLE `picking_posiciones` ADD COLUMN `operacion_id` INT NULL AFTER `id`;
UPDATE `picking_posiciones` SET `operacion_id` = @op_cucuta WHERE `operacion_id` IS NULL;
ALTER TABLE `picking_posiciones`
  MODIFY `operacion_id` INT NOT NULL,
  ADD CONSTRAINT `fk_picking_posiciones_operacion` FOREIGN KEY (`operacion_id`) REFERENCES `operaciones`(`id`);

ALTER TABLE `picking_registros` ADD COLUMN `operacion_id` INT NULL AFTER `id`;
UPDATE `picking_registros` SET `operacion_id` = @op_cucuta WHERE `operacion_id` IS NULL;
ALTER TABLE `picking_registros`
  MODIFY `operacion_id` INT NOT NULL,
  ADD CONSTRAINT `fk_picking_registros_operacion` FOREIGN KEY (`operacion_id`) REFERENCES `operaciones`(`id`);

ALTER TABLE `pi_despachados` ADD COLUMN `operacion_id` INT NULL AFTER `id`;
UPDATE `pi_despachados` SET `operacion_id` = @op_cucuta WHERE `operacion_id` IS NULL;
ALTER TABLE `pi_despachados`
  MODIFY `operacion_id` INT NOT NULL,
  ADD CONSTRAINT `fk_pi_despachados_operacion` FOREIGN KEY (`operacion_id`) REFERENCES `operaciones`(`id`);

ALTER TABLE `pi_reabastecimiento` ADD COLUMN `operacion_id` INT NULL AFTER `id`;
UPDATE `pi_reabastecimiento` SET `operacion_id` = @op_cucuta WHERE `operacion_id` IS NULL;
ALTER TABLE `pi_reabastecimiento`
  MODIFY `operacion_id` INT NOT NULL,
  ADD CONSTRAINT `fk_pi_reabastecimiento_operacion` FOREIGN KEY (`operacion_id`) REFERENCES `operaciones`(`id`);

ALTER TABLE `placas` ADD COLUMN `operacion_id` INT NULL AFTER `id`;
UPDATE `placas` SET `operacion_id` = @op_cucuta WHERE `operacion_id` IS NULL;
ALTER TABLE `placas`
  MODIFY `operacion_id` INT NOT NULL,
  ADD CONSTRAINT `fk_placas_operacion` FOREIGN KEY (`operacion_id`) REFERENCES `operaciones`(`id`);

ALTER TABLE `planeacion_semanal` ADD COLUMN `operacion_id` INT NULL AFTER `id`;
UPDATE `planeacion_semanal` SET `operacion_id` = @op_cucuta WHERE `operacion_id` IS NULL;
ALTER TABLE `planeacion_semanal`
  MODIFY `operacion_id` INT NOT NULL,
  ADD CONSTRAINT `fk_planeacion_semanal_operacion` FOREIGN KEY (`operacion_id`) REFERENCES `operaciones`(`id`);

ALTER TABLE `ptl_areas` ADD COLUMN `operacion_id` INT NULL AFTER `id`;
UPDATE `ptl_areas` SET `operacion_id` = @op_cucuta WHERE `operacion_id` IS NULL;
ALTER TABLE `ptl_areas`
  MODIFY `operacion_id` INT NOT NULL,
  ADD CONSTRAINT `fk_ptl_areas_operacion` FOREIGN KEY (`operacion_id`) REFERENCES `operaciones`(`id`);

ALTER TABLE `ptl_subareas` ADD COLUMN `operacion_id` INT NULL AFTER `id`;
UPDATE `ptl_subareas` SET `operacion_id` = @op_cucuta WHERE `operacion_id` IS NULL;
ALTER TABLE `ptl_subareas`
  MODIFY `operacion_id` INT NOT NULL,
  ADD CONSTRAINT `fk_ptl_subareas_operacion` FOREIGN KEY (`operacion_id`) REFERENCES `operaciones`(`id`);

ALTER TABLE `recargue_t2` ADD COLUMN `operacion_id` INT NULL AFTER `id`;
UPDATE `recargue_t2` SET `operacion_id` = @op_cucuta WHERE `operacion_id` IS NULL;
ALTER TABLE `recargue_t2`
  MODIFY `operacion_id` INT NOT NULL,
  ADD CONSTRAINT `fk_recargue_t_operacion` FOREIGN KEY (`operacion_id`) REFERENCES `operaciones`(`id`);

ALTER TABLE `recursos_almacen` ADD COLUMN `operacion_id` INT NULL AFTER `id`;
UPDATE `recursos_almacen` SET `operacion_id` = @op_cucuta WHERE `operacion_id` IS NULL;
ALTER TABLE `recursos_almacen`
  MODIFY `operacion_id` INT NOT NULL,
  ADD CONSTRAINT `fk_recursos_almacen_operacion` FOREIGN KEY (`operacion_id`) REFERENCES `operaciones`(`id`);

ALTER TABLE `recursos_tv` ADD COLUMN `operacion_id` INT NULL AFTER `id`;
UPDATE `recursos_tv` SET `operacion_id` = @op_cucuta WHERE `operacion_id` IS NULL;
ALTER TABLE `recursos_tv`
  MODIFY `operacion_id` INT NOT NULL,
  ADD CONSTRAINT `fk_recursos_tv_operacion` FOREIGN KEY (`operacion_id`) REFERENCES `operaciones`(`id`);

ALTER TABLE `reempaque1` ADD COLUMN `operacion_id` INT NULL AFTER `id`;
UPDATE `reempaque1` SET `operacion_id` = @op_cucuta WHERE `operacion_id` IS NULL;
ALTER TABLE `reempaque1`
  MODIFY `operacion_id` INT NOT NULL,
  ADD CONSTRAINT `fk_reempaque_operacion` FOREIGN KEY (`operacion_id`) REFERENCES `operaciones`(`id`);

ALTER TABLE `revision` ADD COLUMN `operacion_id` INT NULL AFTER `id`;
UPDATE `revision` SET `operacion_id` = @op_cucuta WHERE `operacion_id` IS NULL;
ALTER TABLE `revision`
  MODIFY `operacion_id` INT NOT NULL,
  ADD CONSTRAINT `fk_revision_operacion` FOREIGN KEY (`operacion_id`) REFERENCES `operaciones`(`id`);

ALTER TABLE `roturas` ADD COLUMN `operacion_id` INT NULL AFTER `id`;
UPDATE `roturas` SET `operacion_id` = @op_cucuta WHERE `operacion_id` IS NULL;
ALTER TABLE `roturas`
  MODIFY `operacion_id` INT NOT NULL,
  ADD CONSTRAINT `fk_roturas_operacion` FOREIGN KEY (`operacion_id`) REFERENCES `operaciones`(`id`);

ALTER TABLE `sectores_almacen` ADD COLUMN `operacion_id` INT NULL AFTER `id`;
UPDATE `sectores_almacen` SET `operacion_id` = @op_cucuta WHERE `operacion_id` IS NULL;
ALTER TABLE `sectores_almacen`
  MODIFY `operacion_id` INT NOT NULL,
  ADD CONSTRAINT `fk_sectores_almacen_operacion` FOREIGN KEY (`operacion_id`) REFERENCES `operaciones`(`id`);

ALTER TABLE `sectores_tv` ADD COLUMN `operacion_id` INT NULL AFTER `id`;
UPDATE `sectores_tv` SET `operacion_id` = @op_cucuta WHERE `operacion_id` IS NULL;
ALTER TABLE `sectores_tv`
  MODIFY `operacion_id` INT NOT NULL,
  ADD CONSTRAINT `fk_sectores_tv_operacion` FOREIGN KEY (`operacion_id`) REFERENCES `operaciones`(`id`);

ALTER TABLE `sider_certificados` ADD COLUMN `operacion_id` INT NULL AFTER `id`;
UPDATE `sider_certificados` SET `operacion_id` = @op_cucuta WHERE `operacion_id` IS NULL;
ALTER TABLE `sider_certificados`
  MODIFY `operacion_id` INT NOT NULL,
  ADD CONSTRAINT `fk_sider_certificados_operacion` FOREIGN KEY (`operacion_id`) REFERENCES `operaciones`(`id`);

ALTER TABLE `sortiing` ADD COLUMN `operacion_id` INT NULL AFTER `id`;
UPDATE `sortiing` SET `operacion_id` = @op_cucuta WHERE `operacion_id` IS NULL;
ALTER TABLE `sortiing`
  MODIFY `operacion_id` INT NOT NULL,
  ADD CONSTRAINT `fk_sortiing_operacion` FOREIGN KEY (`operacion_id`) REFERENCES `operaciones`(`id`);

ALTER TABLE `sorting` ADD COLUMN `operacion_id` INT NULL AFTER `id`;
UPDATE `sorting` SET `operacion_id` = @op_cucuta WHERE `operacion_id` IS NULL;
ALTER TABLE `sorting`
  MODIFY `operacion_id` INT NOT NULL,
  ADD CONSTRAINT `fk_sorting_operacion` FOREIGN KEY (`operacion_id`) REFERENCES `operaciones`(`id`);

ALTER TABLE `tableros` ADD COLUMN `operacion_id` INT NULL AFTER `id`;
UPDATE `tableros` SET `operacion_id` = @op_cucuta WHERE `operacion_id` IS NULL;
ALTER TABLE `tableros`
  MODIFY `operacion_id` INT NOT NULL,
  ADD CONSTRAINT `fk_tableros_operacion` FOREIGN KEY (`operacion_id`) REFERENCES `operaciones`(`id`);

ALTER TABLE `tablero_inventario` ADD COLUMN `operacion_id` INT NULL AFTER `id`;
UPDATE `tablero_inventario` SET `operacion_id` = @op_cucuta WHERE `operacion_id` IS NULL;
ALTER TABLE `tablero_inventario`
  MODIFY `operacion_id` INT NOT NULL,
  ADD CONSTRAINT `fk_tablero_inventario_operacion` FOREIGN KEY (`operacion_id`) REFERENCES `operaciones`(`id`);

ALTER TABLE `tablero_verificaciones` ADD COLUMN `operacion_id` INT NULL AFTER `id`;
UPDATE `tablero_verificaciones` SET `operacion_id` = @op_cucuta WHERE `operacion_id` IS NULL;
ALTER TABLE `tablero_verificaciones`
  MODIFY `operacion_id` INT NOT NULL,
  ADD CONSTRAINT `fk_tablero_verificaciones_operacion` FOREIGN KEY (`operacion_id`) REFERENCES `operaciones`(`id`);

ALTER TABLE `temperaturas` ADD COLUMN `operacion_id` INT NULL AFTER `id`;
UPDATE `temperaturas` SET `operacion_id` = @op_cucuta WHERE `operacion_id` IS NULL;
ALTER TABLE `temperaturas`
  MODIFY `operacion_id` INT NOT NULL,
  ADD CONSTRAINT `fk_temperaturas_operacion` FOREIGN KEY (`operacion_id`) REFERENCES `operaciones`(`id`);

ALTER TABLE `temperatura_au` ADD COLUMN `operacion_id` INT NULL AFTER `id`;
UPDATE `temperatura_au` SET `operacion_id` = @op_cucuta WHERE `operacion_id` IS NULL;
ALTER TABLE `temperatura_au`
  MODIFY `operacion_id` INT NOT NULL,
  ADD CONSTRAINT `fk_temperatura_au_operacion` FOREIGN KEY (`operacion_id`) REFERENCES `operaciones`(`id`);

ALTER TABLE `turnoa_registros` ADD COLUMN `operacion_id` INT NULL AFTER `id`;
UPDATE `turnoa_registros` SET `operacion_id` = @op_cucuta WHERE `operacion_id` IS NULL;
ALTER TABLE `turnoa_registros`
  MODIFY `operacion_id` INT NOT NULL,
  ADD CONSTRAINT `fk_turnoa_registros_operacion` FOREIGN KEY (`operacion_id`) REFERENCES `operaciones`(`id`);

ALTER TABLE `turnob_registros` ADD COLUMN `operacion_id` INT NULL AFTER `id`;
UPDATE `turnob_registros` SET `operacion_id` = @op_cucuta WHERE `operacion_id` IS NULL;
ALTER TABLE `turnob_registros`
  MODIFY `operacion_id` INT NOT NULL,
  ADD CONSTRAINT `fk_turnob_registros_operacion` FOREIGN KEY (`operacion_id`) REFERENCES `operaciones`(`id`);

ALTER TABLE `turnoc_registros` ADD COLUMN `operacion_id` INT NULL AFTER `id`;
UPDATE `turnoc_registros` SET `operacion_id` = @op_cucuta WHERE `operacion_id` IS NULL;
ALTER TABLE `turnoc_registros`
  MODIFY `operacion_id` INT NOT NULL,
  ADD CONSTRAINT `fk_turnoc_registros_operacion` FOREIGN KEY (`operacion_id`) REFERENCES `operaciones`(`id`);

ALTER TABLE `ubicaciones` ADD COLUMN `operacion_id` INT NULL AFTER `id`;
UPDATE `ubicaciones` SET `operacion_id` = @op_cucuta WHERE `operacion_id` IS NULL;
ALTER TABLE `ubicaciones`
  MODIFY `operacion_id` INT NOT NULL,
  ADD CONSTRAINT `fk_ubicaciones_operacion` FOREIGN KEY (`operacion_id`) REFERENCES `operaciones`(`id`);

ALTER TABLE `vertimiento` ADD COLUMN `operacion_id` INT NULL AFTER `id`;
UPDATE `vertimiento` SET `operacion_id` = @op_cucuta WHERE `operacion_id` IS NULL;
ALTER TABLE `vertimiento`
  MODIFY `operacion_id` INT NOT NULL,
  ADD CONSTRAINT `fk_vertimiento_operacion` FOREIGN KEY (`operacion_id`) REFERENCES `operaciones`(`id`);

ALTER TABLE `productividades` ADD COLUMN `operacion_id` INT NULL AFTER `id`;
UPDATE `productividades` SET `operacion_id` = @op_cucuta WHERE `operacion_id` IS NULL;
ALTER TABLE `productividades`
  MODIFY `operacion_id` INT NOT NULL,
  ADD CONSTRAINT `fk_productividades_operacion` FOREIGN KEY (`operacion_id`) REFERENCES `operaciones`(`id`);

-- 4. Tablas con llave primaria de una sola columna: se vuelve compuesta con operacion_id
ALTER TABLE `tiempos_atencion` ADD COLUMN `operacion_id` INT NULL AFTER `fecha`;
UPDATE `tiempos_atencion` SET `operacion_id` = @op_cucuta WHERE `operacion_id` IS NULL;
ALTER TABLE `tiempos_atencion`
  MODIFY `operacion_id` INT NOT NULL,
  DROP PRIMARY KEY,
  ADD PRIMARY KEY (`fecha`, `operacion_id`),
  ADD CONSTRAINT `fk_tiempos_atencion_operacion` FOREIGN KEY (`operacion_id`) REFERENCES `operaciones`(`id`);

ALTER TABLE `config_bloqueo` ADD COLUMN `operacion_id` INT NULL AFTER `mes_anio`;
UPDATE `config_bloqueo` SET `operacion_id` = @op_cucuta WHERE `operacion_id` IS NULL;
ALTER TABLE `config_bloqueo`
  MODIFY `operacion_id` INT NOT NULL,
  DROP PRIMARY KEY,
  ADD PRIMARY KEY (`mes_anio`, `operacion_id`),
  ADD CONSTRAINT `fk_config_bloqueo_operacion` FOREIGN KEY (`operacion_id`) REFERENCES `operaciones`(`id`);

-- 5. Eliminar la funcionalidad de Indice de Frescura (confirmado por el cliente)
-- NOTA: se hace un mysqldump de respaldo de estas 3 tablas antes de correr esta seccion (ver deploy_migration.php).
DROP TABLE IF EXISTS `general`;
DROP TABLE IF EXISTS `mkp`;
DROP TABLE IF EXISTS `picking`;
